
import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Message } from '../types';
import CodeBlock from './CodeBlock';
import { User, Sparkles, Download, Film } from 'lucide-react';

interface MessageBubbleProps {
  message: Message;
}

const MessageBubble: React.FC<MessageBubbleProps> = ({ message }) => {
  const isUser = message.role === 'user';

  const downloadMedia = (url: string, type: 'image' | 'video') => {
    const link = document.createElement('a');
    link.href = url;
    link.download = `balaAI-${type}-${Date.now()}.${type === 'image' ? 'png' : 'mp4'}`;
    link.click();
  };

  return (
    <div className={`flex w-full mb-8 ${isUser ? 'justify-end' : 'justify-start'} animate-in fade-in slide-in-from-bottom-2 duration-500`}>
      <div className={`flex max-w-[85%] md:max-w-[75%] gap-4 ${isUser ? 'flex-row-reverse' : 'flex-row'}`}>
        <div className={`flex-shrink-0 w-9 h-9 rounded-xl flex items-center justify-center shadow-lg ${
          isUser ? 'bg-[#3c3c3c]' : 'bg-gradient-to-tr from-blue-600 via-indigo-500 to-purple-600'
        }`}>
          {isUser ? <User className="w-5 h-5 text-gray-300" /> : <Sparkles className="w-5 h-5 text-white" />}
        </div>
        
        <div className={`flex flex-col ${isUser ? 'items-end' : 'items-start'}`}>
          <div className={`${
            isUser 
              ? 'bg-[#2f2f2f] text-[#e3e3e3] px-5 py-3 rounded-2xl rounded-tr-none border border-[#3c3c3c]' 
              : 'text-[#e3e3e3] w-full'
          }`}>
            {message.imageUrl && (
              <div className="relative group mb-4 rounded-2xl overflow-hidden border border-[#3c3c3c] shadow-2xl bg-[#0d0d0d]">
                <img 
                  src={message.imageUrl} 
                  alt="Generated by balaAI" 
                  className="w-full h-auto max-h-[500px] object-contain transition-transform duration-500 group-hover:scale-[1.02]"
                />
                <div className="absolute top-3 right-3 flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                  <button 
                    onClick={() => downloadMedia(message.imageUrl!, 'image')}
                    className="p-2 bg-black/50 backdrop-blur-md rounded-full text-white hover:bg-black/80 transition-colors"
                  >
                    <Download className="w-4 h-4" />
                  </button>
                </div>
              </div>
            )}

            {message.videoUrl && (
              <div className="relative group mb-4 rounded-2xl overflow-hidden border border-[#3c3c3c] shadow-2xl bg-[#0d0d0d]">
                <video 
                  src={message.videoUrl} 
                  controls 
                  className="w-full h-auto max-h-[500px] rounded-xl"
                />
                <div className="absolute top-3 right-3 flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                  <button 
                    onClick={() => downloadMedia(message.videoUrl!, 'video')}
                    className="p-2 bg-black/50 backdrop-blur-md rounded-full text-white hover:bg-black/80 transition-colors"
                  >
                    <Download className="w-4 h-4" />
                  </button>
                </div>
                <div className="absolute bottom-3 left-3 px-2 py-1 bg-black/50 backdrop-blur-md rounded-md text-[10px] text-white flex items-center gap-1">
                  <Film className="w-3 h-3" />
                  Veo 3.1
                </div>
              </div>
            )}

            {isUser ? (
              <p className="whitespace-pre-wrap leading-relaxed">{message.content}</p>
            ) : (
              <ReactMarkdown
                className="prose prose-invert max-w-none prose-p:leading-relaxed prose-p:mb-4 prose-pre:bg-transparent prose-pre:p-0"
                remarkPlugins={[remarkGfm]}
                components={{
                  code({ node, inline, className, children, ...props }: any) {
                    const match = /language-(\w+)/.exec(className || '');
                    return !inline && match ? (
                      <CodeBlock
                        language={match[1]}
                        value={String(children).replace(/\n$/, '')}
                      />
                    ) : (
                      <code className="bg-[#2f2f2f] px-1.5 py-0.5 rounded text-sm font-mono text-blue-300" {...props}>
                        {children}
                      </code>
                    );
                  },
                }}
              >
                {message.content}
              </ReactMarkdown>
            )}
          </div>
          <span className="text-[10px] text-gray-500 mt-2 px-1 font-medium tracking-tight">
            {new Date(message.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
          </span>
        </div>
      </div>
    </div>
  );
};

export default MessageBubble;
